#!/usr/bin/python3
from __future__ import unicode_literals
import youtube_dl, sys

o = False

try:
    i = str(sys.argv[1])
    o = True

except:
    print("ytToMp3 by Poki")
    print("Usage: ytToMp3 link")
    print("NOTE: Only Youtube links are supported!")

if(o):
    ydl_opts = {
        'outtmpl': '~/Music/%(title)s.%(ext)s',
        'quiet': True,
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
    }
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([i])
