#!/usr/bin/python3
from __future__ import unicode_literals
import youtube_dl, sys, os

o = False

try:
    i = str(sys.argv[1])
    o = True

except:
    print("ytToMp3 by Poki")
    print("Usage: ytToMp3 link")
    print("NOTE: Only Youtube links are supported!")

if(o):
    if os.name == 'nt':
        outtmpl = 'C:\\Users\\' + os.getlogin() + '\\Music\\%(title)s.%(ext)s'
    else:
        outtmpl = '~/Music/%(title)s.%(ext)s'
    ydl_opts = {
        'outtmpl': outtmpl,
        'quiet': True,
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '320',
        }],
    }
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([i])
